import 'dart:io';

import 'package:file_selector/file_selector.dart';
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';

import '../core/app_logger.dart';
import '../models/timing_entry.dart';
import 'json_export_service.dart';

enum ExportFormat {
  json,
  dart,
  flutterPlayer,
  vtt,
  srt,
}

class MultiFormatExportService {
  MultiFormatExportService._();
  static final MultiFormatExportService instance =
      MultiFormatExportService._();

  String generateWebVtt({
    required String lessonId,
    required List<TimingEntry> entries,
  }) {
    final buffer = StringBuffer();
    buffer.writeln('WEBVTT - Muzamin Audio Sync: $lessonId\n');

    for (int i = 0; i < entries.length; i++) {
      final entry = entries[i];
      final start = _formatVttTimestamp(entry.startMs);
      final end = _formatVttTimestamp(entry.endMs);
      final label = entry.effectiveLabel;
      final arabic = entry.textArabic != null && entry.textArabic!.isNotEmpty
          ? '\n${entry.textArabic}'
          : '';

      buffer.writeln('${i + 1}');
      buffer.writeln('$start --> $end');
      buffer.writeln('[${entry.type.name} #${entry.verseNumber}] $label$arabic\n');
    }

    return buffer.toString();
  }

  String generateSrt({
    required List<TimingEntry> entries,
  }) {
    final buffer = StringBuffer();

    for (int i = 0; i < entries.length; i++) {
      final entry = entries[i];
      final start = _formatSrtTimestamp(entry.startMs);
      final end = _formatSrtTimestamp(entry.endMs);
      final label = entry.effectiveLabel;
      final arabic = entry.textArabic != null && entry.textArabic!.isNotEmpty
          ? '\n${entry.textArabic}'
          : '';

      buffer.writeln('${i + 1}');
      buffer.writeln('$start --> $end');
      buffer.writeln('[${entry.type.name} #${entry.verseNumber}] $label$arabic\n');
    }

    return buffer.toString();
  }

  String generateDartSeed({
    required String lessonId,
    required String audioUrl,
    required List<TimingEntry> entries,
  }) {
    final buffer = StringBuffer();
    final safeClassName = _toPascalCase(lessonId.isEmpty ? 'Lesson' : lessonId);

    buffer.writeln('// Generated by Muzamin Studio - ${DateTime.now().toUtc().toIso8601String()}');
    buffer.writeln('// Production-ready data seed for Flutter / Isar / SQLite / Supabase\n');
    buffer.writeln('class ${safeClassName}Seed {');
    buffer.writeln("  static const String lessonId = '$lessonId';");
    buffer.writeln("  static const String audioUrl = '$audioUrl';");
    buffer.writeln('  static const int totalSegments = ${entries.length};');
    buffer.writeln('  static const List<Map<String, dynamic>> segments = <Map<String, dynamic>>[');

    for (final entry in entries) {
      buffer.writeln('    <String, dynamic>{');
      buffer.writeln("      'id': ${entry.id},");
      buffer.writeln("      'number': ${entry.verseNumber},");
      buffer.writeln("      'type': '${entry.type.name}',");
      if (entry.page != null) {
        buffer.writeln("      'page': ${entry.page},");
        buffer.writeln("      'juz': ${entry.juz},");
      }
      buffer.writeln("      'startMs': ${entry.startMs},");
      buffer.writeln("      'endMs': ${entry.endMs},");
      buffer.writeln("      'durationMs': ${entry.durationMs},");
      if (entry.label != null) {
        buffer.writeln("      'label': '${_escapeDart(entry.label!)}',");
      }
      if (entry.textArabic != null) {
        buffer.writeln("      'textArabic': '${_escapeDart(entry.textArabic!)}',");
      }
      buffer.writeln('    },');
    }

    buffer.writeln('  ];');
    buffer.writeln('}\n');

    return buffer.toString();
  }

  String generateFlutterPlayerWidget({
    required String lessonId,
    required String audioUrl,
    required List<TimingEntry> entries,
  }) {
    final safeClassName = _toPascalCase(lessonId.isEmpty ? 'Lesson' : lessonId);
    final buffer = StringBuffer();

    buffer.writeln('// =========================================================================');
    buffer.writeln('// Generated by Muzamin Studio - ${DateTime.now().toUtc().toIso8601String()}');
    buffer.writeln('// Ready-to-use Synchronized Audio Player Widget for Flutter Apps');
    buffer.writeln('// Dependencies: just_audio: ^0.10.4');
    buffer.writeln('// =========================================================================\n');
    buffer.writeln("import 'dart:ui' as ui;");
    buffer.writeln("import 'package:flutter/material.dart';");
    buffer.writeln("import 'package:just_audio/just_audio.dart';\n");
    buffer.writeln('class ${safeClassName}SyncPlayer extends StatefulWidget {');
    buffer.writeln('  const ${safeClassName}SyncPlayer({');
    buffer.writeln('    super.key,');
    buffer.writeln("    this.audioSource = '$audioUrl',");
    buffer.writeln('  });\n');
    buffer.writeln('  final String audioSource;\n');
    buffer.writeln('  @override');
    buffer.writeln('  State<${safeClassName}SyncPlayer> createState() => _${safeClassName}SyncPlayerState();');
    buffer.writeln('}\n');
    buffer.writeln('class _${safeClassName}SyncPlayerState extends State<${safeClassName}SyncPlayer> {');
    buffer.writeln('  late final AudioPlayer _player;');
    buffer.writeln('  final ScrollController _scrollController = ScrollController();');
    buffer.writeln('  int? _activeSegmentIndex;\n');
    buffer.writeln('  static const List<Map<String, dynamic>> _segments = [');

    for (final entry in entries) {
      buffer.writeln('    {');
      buffer.writeln("      'number': ${entry.verseNumber},");
      buffer.writeln("      'type': '${entry.type.name}',");
      if (entry.page != null) buffer.writeln("      'page': ${entry.page},");
      buffer.writeln("      'startMs': ${entry.startMs},");
      buffer.writeln("      'endMs': ${entry.endMs},");
      if (entry.label != null) buffer.writeln("      'label': '${_escapeDart(entry.label!)}',");
      if (entry.textArabic != null) buffer.writeln("      'textArabic': '${_escapeDart(entry.textArabic!)}',");
      buffer.writeln('    },');
    }

    buffer.writeln('  ];\n');
    buffer.writeln('''  @override
  void initState() {
    super.initState();
    _player = AudioPlayer();
    _initAudio();
  }

  Future<void> _initAudio() async {
    try {
      if (widget.audioSource.startsWith('http')) {
        await _player.setUrl(widget.audioSource);
      } else {
        await _player.setFilePath(widget.audioSource);
      }
    } catch (e) {
      debugPrint('Error loading audio: \$e');
    }

    _player.positionStream.listen((pos) {
      final posMs = pos.inMilliseconds;
      final idx = _segments.indexWhere((s) => posMs >= (s['startMs'] as int) && posMs <= (s['endMs'] as int));
      if (idx != -1 && idx != _activeSegmentIndex) {
        setState(() => _activeSegmentIndex = idx);
        _scrollToIndex(idx);
      }
    });
  }

  void _scrollToIndex(int index) {
    if (!_scrollController.hasClients) return;
    const itemHeight = 72.0;
    final target = (index * itemHeight) - 100;
    _scrollController.animateTo(
      target.clamp(0.0, _scrollController.position.maxScrollExtent),
      duration: const Duration(milliseconds: 350),
      curve: Curves.easeInOut,
    );
  }

  @override
  void dispose() {
    _player.dispose();
    _scrollController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    return Scaffold(
      appBar: AppBar(title: const Text('$lessonId - Sync Player')),
      body: Column(
        children: [
          Expanded(
            child: ListView.builder(
              controller: _scrollController,
              padding: const EdgeInsets.all(12),
              itemCount: _segments.length,
              itemBuilder: (context, index) {
                final seg = _segments[index];
                final isActive = index == _activeSegmentIndex;
                final textArabic = seg['textArabic'] as String?;
                final label = seg['label'] as String?;

                return AnimatedContainer(
                  duration: const Duration(milliseconds: 250),
                  margin: const EdgeInsets.symmetric(vertical: 4),
                  decoration: BoxDecoration(
                    color: isActive ? theme.colorScheme.primaryContainer.withValues(alpha: 0.5) : theme.cardColor,
                    borderRadius: BorderRadius.circular(10),
                    border: Border.all(
                      color: isActive ? theme.colorScheme.primary : theme.dividerColor,
                      width: isActive ? 2 : 1,
                    ),
                  ),
                  child: ListTile(
                    leading: CircleAvatar(
                      backgroundColor: isActive ? theme.colorScheme.primary : theme.colorScheme.surfaceContainerHighest,
                      foregroundColor: isActive ? theme.colorScheme.onPrimary : theme.colorScheme.onSurface,
                      child: Text('\${seg['number']}'),
                    ),
                    title: textArabic != null
                        ? Text(
                            textArabic,
                            textDirection: ui.TextDirection.rtl,
                            style: TextStyle(
                              fontSize: 16,
                              fontWeight: isActive ? FontWeight.bold : FontWeight.normal,
                              color: isActive ? theme.colorScheme.primary : null,
                            ),
                          )
                        : Text(label ?? ''),
                    subtitle: Text('\${(seg['startMs'] / 1000).toStringAsFixed(1)}s → \${(seg['endMs'] / 1000).toStringAsFixed(1)}s'),
                    onTap: () => _player.seek(Duration(milliseconds: seg['startMs'] as int)),
                  ),
                );
              },
            ),
          ),
          Container(
            padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
            decoration: BoxDecoration(
              color: theme.colorScheme.surface,
              boxShadow: const [BoxShadow(color: Colors.black12, blurRadius: 8)],
            ),
            child: Row(
              children: [
                StreamBuilder<PlayerState>(
                  stream: _player.playerStateStream,
                  builder: (context, snap) {
                    final playing = snap.data?.playing ?? false;
                    return IconButton.filled(
                      onPressed: () => playing ? _player.pause() : _player.play(),
                      icon: Icon(playing ? Icons.pause_rounded : Icons.play_arrow_rounded),
                    );
                  },
                ),
                const SizedBox(width: 12),
                Expanded(
                  child: StreamBuilder<Duration>(
                    stream: _player.positionStream,
                    builder: (context, posSnap) {
                      final pos = posSnap.data ?? Duration.zero;
                      final dur = _player.duration ?? Duration.zero;
                      final maxVal = dur.inMilliseconds > 0 ? dur.inMilliseconds.toDouble() : 1.0;
                      final val = pos.inMilliseconds.toDouble().clamp(0.0, maxVal);

                      return Slider(
                        value: val,
                        max: maxVal,
                        onChanged: (v) => _player.seek(Duration(milliseconds: v.toInt())),
                      );
                    },
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}
''');

    return buffer.toString();
  }

  Future<String?> exportFormattedFile({
    required ExportFormat format,
    required String lessonId,
    required String audioUrl,
    required List<TimingEntry> entries,
  }) async {
    if (entries.isEmpty) {
      throw const ExportException('لا توجد توقيتات مسجلة للتصدير.');
    }

    final String content;
    final String extension;
    final String label;

    switch (format) {
      case ExportFormat.vtt:
        content = generateWebVtt(lessonId: lessonId, entries: entries);
        extension = 'vtt';
        label = 'WebVTT';
        break;
      case ExportFormat.srt:
        content = generateSrt(entries: entries);
        extension = 'srt';
        label = 'SubRip SRT';
        break;
      case ExportFormat.dart:
        content = generateDartSeed(
          lessonId: lessonId,
          audioUrl: audioUrl,
          entries: entries,
        );
        extension = 'dart';
        label = 'Dart Seed Code';
        break;
      case ExportFormat.flutterPlayer:
        content = generateFlutterPlayerWidget(
          lessonId: lessonId,
          audioUrl: audioUrl,
          entries: entries,
        );
        extension = 'dart';
        label = 'Flutter Sync Player';
        break;
      case ExportFormat.json:
        throw UnimplementedError('استخدم JsonExportService للتصدير إلى JSON');
    }

    final safeName = _safeFileName(lessonId.isEmpty ? 'sync' : lessonId);
    final suffix = format == ExportFormat.flutterPlayer ? '_player' : '';
    final suggestedName = '$safeName${suffix}_${DateTime.now().millisecondsSinceEpoch}.$extension';

    final targetPath = await _resolveTargetPath(suggestedName, extension, label);
    if (targetPath == null) return null;

    try {
      await File(targetPath).writeAsString('$content\n', flush: true);
      AppLogger.instance.info('تم تصدير ملف $label بنجاح إلى: $targetPath');
      return targetPath;
    } catch (e, stack) {
      AppLogger.instance.error('فشل تصدير ملف $label', e, stack);
      throw ExportException('خطأ في حفظ الملف: $e');
    }
  }

  static String _formatVttTimestamp(int totalMs) {
    final ms = (totalMs % 1000).toString().padLeft(3, '0');
    final totalSeconds = totalMs ~/ 1000;
    final s = (totalSeconds % 60).toString().padLeft(2, '0');
    final mm = ((totalSeconds ~/ 60) % 60).toString().padLeft(2, '0');
    final h = (totalSeconds ~/ 3600).toString().padLeft(2, '0');
    return '$h:$mm:$s.$ms';
  }

  static String _formatSrtTimestamp(int totalMs) {
    final ms = (totalMs % 1000).toString().padLeft(3, '0');
    final totalSeconds = totalMs ~/ 1000;
    final s = (totalSeconds % 60).toString().padLeft(2, '0');
    final mm = ((totalSeconds ~/ 60) % 60).toString().padLeft(2, '0');
    final h = (totalSeconds ~/ 3600).toString().padLeft(2, '0');
    return '$h:$mm:$s,$ms';
  }

  static String _safeFileName(String input) {
    return input.replaceAll(RegExp(r'[^a-zA-Z0-9_\-\.]'), '_');
  }

  static String _toPascalCase(String input) {
    final clean = input.replaceAll(RegExp(r'[^a-zA-Z0-9]'), ' ');
    return clean
        .split(' ')
        .where((s) => s.isNotEmpty)
        .map((s) => s[0].toUpperCase() + s.substring(1))
        .join();
  }

  static String _escapeDart(String text) {
    return text.replaceAll(r'\', r'\\').replaceAll("'", r"\'").replaceAll(r'$', r'\$').replaceAll('\n', r'\n');
  }

  static Future<String?> _resolveTargetPath(
    String suggestedName,
    String extension,
    String label,
  ) async {
    try {
      final location = await getSaveLocation(
        suggestedName: suggestedName,
        acceptedTypeGroups: [
          XTypeGroup(
            label: '$label (*.$extension)',
            extensions: [extension],
          ),
        ],
      );
      if (location != null) return location.path;
    } catch (_) {}

    final dir = await getApplicationDocumentsDirectory();
    final outDir = Directory(p.join(dir.path, 'TafsirTimingTool_Exports'));
    if (!outDir.existsSync()) {
      outDir.createSync(recursive: true);
    }
    return p.join(outDir.path, suggestedName);
  }
}
